TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#DATA += ioc_stats_clust.opi
#DATA += ioc_stats_epics_env.opi
#DATA += ioc_stats_limits.opi
#DATA += ioc_stats_reboot_confirm.opi
#DATA += ioc_stats_reloadacf_confirm.opi
#DATA += ioc_stats_soft.opi
#DATA += ioc_stats_vxworks.opi

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
